ERROR:root:Error running Test.py: Traceback (most recent call last):
  File "/home/frank1o3/shared/Proxy/Test.py", line 14, in <module>
    main()
    ^^^^
NameError: name 'main' is not defined. Did you mean: 'min'?

